image:
  file: .gitpod.Dockerfile
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
tasks:
  - init: pip3 install numpy glob3 pygame 
    command: python3 sudoku_game_audio_off.py
