image: gitpod/workspace-full-vnc
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
tasks:
  - init: pip3 install numpy glob3 itertools pygame
    command: python3 sudoku_game.py